package com.bookstore.demo.model;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table book_order
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class BookOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_order.order_number
     *
     * @mbg.generated
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_order.book_number
     *
     * @mbg.generated
     */
    private String bookNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_order.order_number
     *
     * @return the value of book_order.order_number
     *
     * @mbg.generated
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_order.order_number
     *
     * @param orderNumber the value for book_order.order_number
     *
     * @mbg.generated
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_order.book_number
     *
     * @return the value of book_order.book_number
     *
     * @mbg.generated
     */
    public String getBookNumber() {
        return bookNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_order.book_number
     *
     * @param bookNumber the value for book_order.book_number
     *
     * @mbg.generated
     */
    public void setBookNumber(String bookNumber) {
        this.bookNumber = bookNumber;
    }
}