package com.bookstore.demo.mapper;

import com.bookstore.demo.model.BookOrder;
import com.bookstore.demo.model.BookOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_order
     *
     * @mbg.generated
     */
    long countByExample(BookOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_order
     *
     * @mbg.generated
     */
    int deleteByExample(BookOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("orderNumber") String orderNumber, @Param("bookNumber") String bookNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_order
     *
     * @mbg.generated
     */
    int insert(BookOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_order
     *
     * @mbg.generated
     */
    int insertSelective(BookOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_order
     *
     * @mbg.generated
     */
    List<BookOrder> selectByExample(BookOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BookOrder record, @Param("example") BookOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BookOrder record, @Param("example") BookOrderExample example);
}