package com.bookstore.demo.mapper;

import com.bookstore.demo.model.Orderlist;
import com.bookstore.demo.model.OrderlistExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface OrderlistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlist
     *
     * @mbg.generated
     */
    long countByExample(OrderlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlist
     *
     * @mbg.generated
     */
    int deleteByExample(OrderlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlist
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String orderNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlist
     *
     * @mbg.generated
     */
    int insert(Orderlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlist
     *
     * @mbg.generated
     */
    int insertSelective(Orderlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlist
     *
     * @mbg.generated
     */
    List<Orderlist> selectByExample(OrderlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlist
     *
     * @mbg.generated
     */
    Orderlist selectByPrimaryKey(String orderNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlist
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Orderlist record, @Param("example") OrderlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlist
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Orderlist record, @Param("example") OrderlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlist
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Orderlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlist
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Orderlist record);
}